# Generated by Django 5.0.4 on 2025-03-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("transaction_Description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("type", models.CharField(max_length=255)),
                ("user_id", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "finance",
            },
        ),
    ]
