# Generated by Django 5.0.4 on 2025-03-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("sender", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
